#Independent settings for the planner's costmap
global_costmap: 
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 1.0
  rolling_window: false
  plugins:
   - {name: static_map,       type: "common_costmap_plugins::StaticCostmapPlugin"}
   - {name: obstacles,        type: "common_costmap_plugins::ObstacleCostmapPlugin"}
   - {name: foot,            type: "common_costmap_plugins::FootprintCostmapPlugin"}
   - {name: inflater,         type: "common_costmap_plugins::InflationCostmapPlugin"}
   - {name: social,           type: "social_costmap_plugin::SocialCostmapPlugin"}
