#Independent settings for the planner's costmap
global_costmap: 
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 1.0
  rolling_window: false
  plugins:
   - {name: static_map,       type: "costmap_2d::StaticLayer"}
   - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
   - {name: foot,            type: "costmap_2d::FootprintLayer"}
   - {name: inflater,         type: "costmap_2d::InflationLayer"}

