local_costmap:
  #Independent settings for the local costmap
  global_frame: odom_combined
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0
  plugins:
   - {name: obstacles,        type: "common_costmap_plugins::ObstacleCostmapPlugin"}
   - {name: footy,            type: "common_costmap_plugins::FootprintCostmapPlugin"}
   - {name: inflater,         type: "common_costmap_plugins::InflationCostmapPlugin"}