local_costmap:
  #Independent settings for the local costmap
  global_frame: odom_combined
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0
  plugins:
   - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
   - {name: footy,            type: "costmap_2d::FootprintLayer"}
   - {name: inflater,         type: "costmap_2d::InflationLayer"}
  obstacles:
   publish_voxel_map: true
